runtime: php  # language of the app
env: flex     # let app engine know we use flexible environment

runtime_config:
    document_root: public   #folder where index.php is

# Ensure we skip ".env", which is only for local development
skip_files:
    - .env #we want to skip this to make sure we don’t mess stuff up on the server

env_variables:
    # Put production environment variables here.
    APP_NAME: E-Commerce
    APP_ENV: local   # or production
    APP_DEBUG : true # or false
    APP_KEY: base64:ezutoOQCugBReIhBbFlNopgWNvB78eXGXfPgGgFGXRc=
    #go to generate app key paragraf in this tutorial

    CACHE_DRIVER: database

    # instead of putting the cache in the database I recommend using redis
    SESSION_DRIVER: database #or file since both work

    APP_LOG: daily
    APP_TIMEZONE: UTC #your timezone of choice


    # follow the part of the tutorial on setting up your SQL database
    DB_CONNECTION: mysql
    DB_HOST: 35.200.240.243
    DB_PORT: 3306
    DB_DATABASE: ecommerce
    DB_USERNAME: root
    DB_PASSWORD: bunty3030
    DB_SOCKET: /cloudsql/ecommerce-250805:asia-south1:ecommercedb

# Use the connection name obtained when configuring your Cloud SQL instance.
beta_settings:
    cloud_sql_instances: "ecommerce-250805:asia-south1:ecommercedb"
